apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photostudio-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amritha1503/PhotoStudio-Project
    path: charts/photostudio-app
    targetRevision: azure-devops
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: final
  syncPolicy:
    automated:
      prune: true
      enabled: true
